package com.theoplayer.android.ui.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF775A00)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFFFDF98)
internal val md_theme_light_onPrimaryContainer = Color(0xFF251A00)
internal val md_theme_light_secondary = Color(0xFF6A5D3F)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFF4E0BB)
internal val md_theme_light_onSecondaryContainer = Color(0xFF241A04)
internal val md_theme_light_tertiary = Color(0xFF496548)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFCBEBC6)
internal val md_theme_light_onTertiaryContainer = Color(0xFF06210A)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFFFBFF)
internal val md_theme_light_onBackground = Color(0xFF1E1B16)
internal val md_theme_light_surface = Color(0xFFFFFBFF)
internal val md_theme_light_onSurface = Color(0xFF1E1B16)
internal val md_theme_light_surfaceVariant = Color(0xFFECE1CF)
internal val md_theme_light_onSurfaceVariant = Color(0xFF4D4639)
internal val md_theme_light_outline = Color(0xFF7E7667)
internal val md_theme_light_inverseOnSurface = Color(0xFFF7F0E7)
internal val md_theme_light_inverseSurface = Color(0xFF33302A)
internal val md_theme_light_inversePrimary = Color(0xFFFFC50F)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF775A00)
internal val md_theme_light_outlineVariant = Color(0xFFD0C5B4)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFFFFC50F)
internal val md_theme_dark_onPrimary = Color(0xFF3F2E00)
internal val md_theme_dark_primaryContainer = Color(0xFF5A4300)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFFFDF98)
internal val md_theme_dark_secondary = Color(0xFFD7C5A0)
internal val md_theme_dark_onSecondary = Color(0xFF3A2F15)
internal val md_theme_dark_secondaryContainer = Color(0xFF52452A)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFF4E0BB)
internal val md_theme_dark_tertiary = Color(0xFFAFCFAB)
internal val md_theme_dark_onTertiary = Color(0xFF1C361D)
internal val md_theme_dark_tertiaryContainer = Color(0xFF324D32)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFCBEBC6)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF1E1B16)
internal val md_theme_dark_onBackground = Color(0xFFE9E1D9)
internal val md_theme_dark_surface = Color(0xFF1E1B16)
internal val md_theme_dark_onSurface = Color(0xFFE9E1D9)
internal val md_theme_dark_surfaceVariant = Color(0xFF4D4639)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFD0C5B4)
internal val md_theme_dark_outline = Color(0xFF999080)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
internal val md_theme_dark_inverseSurface = Color(0xFFE9E1D9)
internal val md_theme_dark_inversePrimary = Color(0xFF775A00)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFFFFC50F)
internal val md_theme_dark_outlineVariant = Color(0xFF4D4639)
internal val md_theme_dark_scrim = Color(0xFF000000)


private val seed = Color(0xFFFFC50F)
