name: CI
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Assemble
        run: ./gradlew assembleRelease --configuration-cache
      - name: Assemble with lowest supported player version
        run: ./gradlew assembleRelease --configuration-cache -PinstallLowestSupportedPlayerVersion=true
      - name: Run tests
        run: ./gradlew test --configuration-cache
