name: CI
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          # https://github.com/gradle/actions/blob/v6.0.0/README.md#licensing-notice
          cache-disabled: true
      - name: Run tests
        run: ./gradlew test
      - name: Assemble
        run: ./gradlew assembleRelease
