name: CI
on:
  push:
    branches:
      - main
      - next
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Assemble
        run: ./gradlew assembleRelease
